name: Generate and Commit Files

on: pull_request

jobs:
  generate-and-commit-files:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: refs/pull/${{ github.event.pull_request.number }}/head
          # ref: ${{ github.head_ref }}
          # ref: ${{github.event.pull_request.head.ref}}

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm ci

      - name: Generate test and review files
        run: npm run build

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Generate test and review files automatically

  generate-and-commit-files-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: refs/pull/${{ github.event.pull_request.number }}/head
          # ref: ${{ github.head_ref }}
          # ref: ${{github.event.pull_request.head.ref}}

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: npm ci

      - name: Generate test and review files
        run: npm run build
